//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; E:\TOMAS_G\I-C\Arduino0.py
///  Source class: Servo
///  Generation timestamp: 2019-06-25T19:08:31.863851
///  Class code hash: cf4f85ed888f284b59884ff3ad75b9c079d5f6e9
///
/////////////////////////////////////////////////////////////


#include "inodriver_bridge.h"

SerialCommand sCmd;

void ok() {
  Serial.println("OK");
}

void error(const char* msg) {
  Serial.print("ERROR: ");
  Serial.println(msg);
}

void error_i(int errno) {
  Serial.print("ERROR: ");
  Serial.println(errno);
}

void bridge_loop() {
  while (Serial.available() > 0) {
    sCmd.readSerial();
  }
}

void bridge_setup() {
  //// Setup callbacks for SerialCommand commands

  // All commands might return
  //    ERROR: <error message>

  // All set commands return 
  //    OK 
  // if the operation is successfull

  // All parameters are ascii encoded strings
  sCmd.addCommand("INFO?", getInfo); 

  sCmd.setDefaultHandler(unrecognized); 


  // angle
  // <F> float as string 

  // Setter:
  //   ANGLE <F> 
  // Returns: OK or ERROR    
  sCmd.addCommand("ANGLE", wrapperSet_ANGLE); 
}

//// Code 

void getInfo() {
  Serial.print("Servo,");
  Serial.println(COMPILE_DATE_TIME);
}

void unrecognized(const char *command) {
  error("Unknown command");
}
//// Auto generated Feat and DictFeat Code
// COMMAND: ANGLE, FEAT: angle

void wrapperSet_ANGLE() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  float value = atof(arg);

  int err = set_ANGLE(value);
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};



