//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; E:\TOMAS_G\I-C\Arduino0.py
///  Source class: Servo
///  Generation timestamp: 2019-06-25T19:08:31.863851
///  Class code hash: cf4f85ed888f284b59884ff3ad75b9c079d5f6e9
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_bridge_h
#define inodriver_bridge_h

#include <Arduino.h>

#include "SerialCommand.h"

#include "inodriver_user.h"

const char COMPILE_DATE_TIME[] = __DATE__ " " __TIME__;

void ok();
void error(const char*);
void error_i(int);
void bridge_loop();
void bridge_setup();

void getInfo();
void unrecognized(const char *);
void wrapperSet_ANGLE(); 


#endif // inodriver_bridge_h