//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; E:\TOMAS_G\I-C\Arduino0.py
///  Source class: Servo
///  Generation timestamp: 2019-06-25T19:08:31.870850
///  Class code hash: cf4f85ed888f284b59884ff3ad75b9c079d5f6e9
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
int set_ANGLE(float); 


#endif // inodriver_user_h